#!/bin/sh
# loopmount a device

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions
# Begin real processing below this line

info() {
	_log_msg "Info: $*\\n"
}
success() {
	log_success_msg "$*"
}
warn() {
	log_warning_msg "$*"
}
err() {
	log_failure_msg "$*"
}
fatal() {
	log_failure_msg "$*"
}
debug() {
	[ ! -z "${debug}" ] && _log_msg "Debug: $*\\n"
}

#panic() is already defined

. /usr/lib/looproot/mount_loop_as_rootfs

return $?
